---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-pull-secret
  namespace: stock
spec:
  encryptedData:
    .dockerconfigjson: AgCBC5CrLUGJgPT6YiK6M8QiZ0pqWythtG0u8eqWKNT5GepJXPPjdpWsmJj1s4l/TJVa6se4hcf8D7hf/KL75RgOcrmk0TB4MsvIIcfZ3px6BrBQ1D8d6oT+bjStNI6CcvGcXHgdTUHPWKQSlDg3HGzYMhsEWc5mLeV/n+YokeBo/JQDI509jaxjrDx5NgQL6gHBwAR+jVY2yynlE4a62WSOxleMIJnUvC8hmXceeU/T3lXx0ToHFJ7T4as2Yqe8ipBLS/zfQQ4d8rOzCH+d0zVR9StbQNtlgQcVnHH4DS0rRTLRvbx+QW0xvChUYQDGM6kf/K3eWWE8zRDSy1JYzUZaO9SI2tsmR519+nSSbErCY2WsUQDo55fo+yevY4w6Wgd97UfNCGmIKOxOzAo8A2XbJ1NhhAqyEUWbznjaMpkxPqXkz9R9xg9t4A9iDC+9YeRaHV5A2o31ZGRcetlXtVB6sVn9gazYx/W2wBx5MiZYzg1LJ3cjkeobjzmBAMh2Sv2xNYxVXZFtyV4EFBccdMVKAnDiyvzOfDDQOkCGvwfcZWeXlOKO8MjAB96mwHrflb4ti2Cpgu4bXXoP7LMjyyZlZaduuzdKacIzQ/IREAnqHCTy2tklou4jHjH0CvHX79jOEMzjuiP9mKGb1nQDyk/CFmITsN1xRsBYAzodWos/KjeE+sYQC/FsIpi7I6bf+OwkrbpxvoNWCo67DWjwNR5JneNRh9WmvRltDB+huWfy0QFaFBaWD+EQubOoZSXp9ozCIDjFHDk8sZJvKi5uiBHFnR3HlJsrFBnnbNrJtkIpil1FOiEhXV09YCLThxg7zZ1MWtf1htI1
  template:
    metadata:
      creationTimestamp: null
      name: harbor-pull-secret
      namespace: stock
    type: kubernetes.io/dockerconfigjson
