---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-pull-secret
  namespace: stock
spec:
  encryptedData:
    .dockerconfigjson: AgCN75yC5+ywPL5Rzi3UU9vLjmMQrXsONwSkCJ9hhOSHwYsHRbOhw0e+OzucjSCDD01B7ND4kgfTtZm4IocfjQMn0McMRiuNj3/YZRGP+GZgqcOIDXzlEBZmR5X7r0VT94xFizRSyAKBIlVY0gpagj7bi278tyK8phCSkQHlICOu0WFiWlyn6PpifHZRVmv8QpCTDEIi5ROCqYwt6q5WtU1V/PR1iNc6rzbb3MRHxdbhfFDVzE7ooOGTFwI0fO25+iZey0zhEkKbrSWdRTOemrAeBe1Rk7hBy4yMaXLFmKt+3ZVi9Rt+o4/qoRCZzZuac8rn/z2WbeCqznCQRg+5zDGddh9pP9wf0qE8eH81quEpTNfcx6pwibnw9Tm+ZeOqWzH1Gvj/IsPfCbATJYwDka5P+fMeOGrDiBMWiPuZcQzbRE2e8rjov+OGZK+gZcBYVi78IzsdJNRY3M6DOXEC96pJYamuKpuSgpL7qP/7yoYlhDSIpoCEaHKfSlD5SsVNdpIpLuLhpk6IJzHWVCfGyUlkqkPNAKo5er+FzGmzqNGSq63EZMNQrTdltxJ/AD9M0rsLgn5z5UnvICKuiXXVvitdtZEY4NjvQhWx7+6yaIw6jglzUI/T4wMYPEaHDYcwDxfkcLDo7cNPqY0fDBmdfNTjyWbuMa6Zu+bTpdNUdDmkhQwvUxDT+xU7o768GM+zJ4H/3ZfyYF+X2z2tmgm6QJQuAG0K3vQrp/D82e3jzKouLwGf4kDtr2batveMfW3MK/U/jZGFkNF9K3vt4ae1+VecXowzOWv+om4unBIFwsOdvwhAWOOezvG28W9nLtYRHj1ZpMYZNVM8
  template:
    metadata:
      creationTimestamp: null
      name: harbor-pull-secret
      namespace: stock
    type: kubernetes.io/dockerconfigjson
