---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-pull-secret
  namespace: stock
spec:
  encryptedData:
    .dockerconfigjson: AgBxG/ekKb4oNVLuJmH+/mju3t0XrDpdKrJilpa2JKjN6sRnCL09G3uG3hQC9NaGXbmWKwW88KJd4o9DXtx2E+sNEzDdHOjyuu0H/sG2N/sdscGDiARs3kXvwcd8trJBZ/cL/9yglo+YkOOTiYqxVcrlovWPx4q8HoabahqmRSiHkCVuhE0wvkgH8jDBtbnNH07yPuPUPRXvpRWJjDJXuKTzd/6WtwElOcO5xBIw3yAsdALJKLSvx+UKFHvEofWVJAY8jMARUM/Cp9pRBDK+YTnvOHX+uwXWX20EPrnDKq+ZaiMw0DECgJ3QQgyMqaFHGuJDF2ELrsMt/2a03lzQxk8w9GbKr6J422zDNOFfYR0VzDfqQid8ObJwSPCVxayhNCe/1ffQDLFS+pyaAzPK6wsPkCphvO7h5pmi2AcF5JQukchr+KELgYUhIHZfuz1U2UV2uspAP9OT0rBpbJrxYQfWwFyW8qj8UY7OQIGojDshPiSOenovwQRpop83grXXU/sDP+SlFQV5xpobe4Zweb2xSAIJdQ2z6/pjwd4QAW0cSbaJc/9cs7pWhsqOy//x50///tlC4ZL7TS3yOZ3CCAQmRMxuyqIIHbeT9hJCJhQE6lOe/DQVD1NafsugvZq7KXMTEodUq9ZwuExQ+u1ax+8+eOWy5eG4pqNcvv7MjK3pPQ6gHwNfgrH2dLN+rOj3LVMjiphKzsda5oY5AbiHvtB8uNJdcREVKNv30rdnu84FvfQfBeDJfB+Fqm3c3YbORrYfpvb510et08BO+4AxG0DM4l9TVnraJU2heUKqJRgE4Dux+ajj543BPg0GRqDY26FKxw7lQkYi
  template:
    metadata:
      creationTimestamp: null
      name: harbor-pull-secret
      namespace: stock
    type: kubernetes.io/dockerconfigjson
