---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: stock-auth-secret
  namespace: stock
spec:
  encryptedData:
    JWT_SECRET: AgApaw2Km5MhrvPfAnBNOBYy3qB5aVTQFRmvZPIyHy7gs3N5hbkiR/tTGZeOsqt5Q6/ZlUZb9Oi7HaVeFW0fl57gRor44OA3UzsjJeZO/YOrouYZ5efX3bwRKin4fx44poQGFCnqfXMBo+UPLrz4kDCwdedQYMhQaxhgWNUb5CqtkdM8u1xVrfuQfYo3Yq61lnjaz1Kc9EAZI/wAwzn4doOnPYdf8jDcXzgyjhbLCotyj8SJgWFEy9J7Yebi7WSjZ2z7oonIfZS0a5NNe5oahWK/9oAB/DBODs3qrePos343wVXaaO7UhAnlZyTMMCFyvbn3A46eutN570sbnToVzjEd71RxAlGdSjfeRHdwVMImy7Sbg9I5x/q/XFERdU2lI4D77W3QHDmG2UP3nm88xu2E/dCreBAVAz51lhkaz2acRVeXG3i84ty6qZUl+dfGB/aD4uRD8iKY5EceLHxwmoNPsasK0lbBjw9FzuxmITee304u8saW8WCs/UkFz0yWLBUMXTfvnvhouhIsIIz42NP+JPLqUQqihJSUCIBf21sregK1Efy2pODB7/JXvCgRV2A1tdGpIVTbj141K/FH7V20v5ejriWWCmsueUb51Qqnjjnyz52hf7YvWYmKMzO12MTHZXdrupalAUkIkX9nyNK4BKu+YoIsEs6AhhpUdRH6wMVwmZcxDejc5x4jFGsr7I9r7OZloil7jLu6MEKb67C/651OcMrjmlI6zWFabAK8Lz2wyIzkvQiner7bi9DvxxkvqJedO3LVag/gS2CkWzio
  template:
    metadata:
      creationTimestamp: null
      name: stock-auth-secret
      namespace: stock
