---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: stock-api-secrets
  namespace: stock
spec:
  encryptedData:
    GEMINI_API_KEY: AgCV2FDQ/JiqsZuvwVvI1xDcMDm0GOkWDfZ0aNywIbOBYC4P2thM6gnfcTfzvqIjCpJRk0O+EKnGIO/WCc1mRrSGXfjbZ2teNhf+y3ZAFsb+IRFBeigdZL/sarduBT1bZIvKWoPykzZhvi14/lrGcoY4oAsXsrDFVicSCJos8UZq4/IHKawTkV4GEgngjYHvrORJgngl+ohVW7DWzQNG8LlDJDgsWjyI7qUz8OpIj8rMBGy3SntHaysKXtw8SMEDvZwj57Bcd0VqcYfxb96A6U1amZJtT4pMBdIiZ3vNEMBd3FVo5sIG+qwAWxZU5mrPrsiUDC66wJvSO31R1Fs+ViEMnvdrxk3bJpssttnDG6XyerOCkImnwqhdjlyhIstj2iJw3Zjab63ddc6e304iZLQUSboJMPfNi3alw33Msmw15cbxR+ouEMWDRHPKp3lvbYvY5h6v9rIhjIx4YTRLw0+dNxfaUiV3LMvHwEtUMH4uEBAwl0NVsBaAq1Sz4vWMvK5L7MR0/Cw8ECyz2jL724fsYLEvs0bY4AK5zWfTRcN/BCXnLHD/BrX/4mSq2GgaqikNTbEHUA/D0iwoOBgfbS90ifc2WgzRjbFEghFEXv2M++XlOAD4IfIn9Ya47yyR6G/tUGWrIHYwHcKNLSKjGAcxWnkxD3VmZYZp+Az3e3+QruXaYDxHMbDkNSsi+2xCvyg1Hl6xLU+SOgsf/1zvlzsv75u6AEX2Brv7KvcsbfSiK7ecqpdGoUE=
    NEWS_API_KEY: AgAKmGBXFAtPxMkNW0w0EQCu1u1B9R2cvkxlKiswhZnID5LKTbzzMllFYMvf5rG4xLddCQueEXYD7o68Zb1cmFnmYuBnrrIQ3LyiGubS0RsIsnocYVulkGuUk+d9ioG1DaAcyJAkKqgvDNn6aGTTc2LInXyc+5sfYvedqCvfzDkPAu9kXjcqmYrn/2AxgyY9N/saUeskZCAjKTcYcdwlfPzKl4R3s7o5lUgRGdStZ2HwYsWifOpfUCJ0f2ZS8cEgn/6NC/RDgI0mseEglmsENCAhVWb1ivmMifpvnPPu5RVjY3KO0UMS8AdaN4uB7HqE8XRH/C84TWEeJu6nd+bf4Y1v7VKJsOb0JVoAW43Dd5KDBqbP2x6fvJCN9j+eegYdE0iusR2HQjwRTVBZEMuBFVtxZG+BZV3Y2fQ3DKQRQzNNu1A9ZHQCoWwzBQ+B7zkWpxN3XkmrmEd7UTT0JHKSuaS9a3bxIh4J3TsCNDF6SuPq/Rz0x9Bhb4XtnCGg/Ocj1aJLh61vrm5JJHkiylBy/1bFJOlhKqVuFhiMF6Nw90iHpRMFdp1EhWj+lGpiUCmDnvtq7Uod5sCisoJR27bOB3ShRjUyY5moYsV30SPAZwpnk0qqwwqGspBxKKs6ODSGdrNZM7I+aKpGj8TfbY4/s3cPdiDaVBa3HBEbUKMW8ZRyKyPwT4BFjfKQ1O22Tzp828kC4bQF1vW2/2E28SocaytyDxUGjRn76xGIO0JlvwIheQ==
  template:
    metadata:
      creationTimestamp: null
      name: stock-api-secrets
      namespace: stock
