---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: stock-notifier-secret
  namespace: stock
spec:
  encryptedData:
    SLACK_WEBHOOK_URL: AgBlB59V7bp6NC+4Db0NaMunqo4wAHOTyQT4qTMsM5e8NkN4GQ2bJqgS5DTxUxJBXqBiu3ZS4QrXTX2X2EneeLY+NJDKbL+kvvXEDbqaNj01a7xxu+DdHgWeRIphX5NLFPN4u8t7>
  template:
    metadata:
      creationTimestamp: null
      name: stock-notifier-secret
      namespace: stock
