---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: stock-notifier-secret
  namespace: stock
spec:
  encryptedData:
    SLACK_WEBHOOK_URL: AgB3ffKI7otnsf1Bwbeobw5mQRrk9auXv+4ygcjwwGohTnYIcJUvRO2qMS5TogR8ExNNAZYefp+usZp0i8posGwq5BWuGLcRrwHHaeQ7ZpVvnYRVzSZnH0QYTorfuzOQA6yJLNw2RJzxYN87r4hzzmYzBDKhU6QYFsma3ZOBi/9oA1AHPtx7Cm/WYeIVi7rEh5AR2MrDEJzShaPuP7oCpaudZSEJqNcEEJaxf4dfOQtUQxd7mOOOCJONcu3R7JITESc+516KR5Kmn1RWhP//1+hukEND2FzoM/CkjSh3TMOk5D3HSn0AvgLUehoEHmCZBO1jVh693NZSMgot6hCGyVqz+ffKyrGqBWh8u957OjCnkmTExF7AluBXl4dzNujJktQFieMScYTUocoXC6Rps6yL6YPnRUevOsKixKFVlIfdY9tsc8akIHL/OuucMnZjJwec104RtmZ/bwfX1YGpVoL6bmvrwK9dQffZlzygXdFHAtJpE6uYyPddwDHrZddEHTmTMy93qU/kBiiOl0JYi6ue9mjAIHe7x8xVi3EgQ+zKOdpzmamVe0RS6WSYVy4FLGM41QnZXxLXanfYiOZigUKvoJV50qTHSEeQB87i4ah0ROyKyMEeO179xo5EtcFd3qPHNo3BGHRJ0NyiNhU+Or1rupPj53OmcjKuUBnrGnWt0FTR15WvkUItGaP8H3AFdAkFOdSya0jgw4H0kg==
  template:
    metadata:
      creationTimestamp: null
      name: stock-notifier-secret
      namespace: stock
