---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: stock-db-secret
  namespace: stock
spec:
  encryptedData:
    POSTGRES_DB: AgBt3m84ljLezlWByWuIEqTq/TNPf5kR2PcLSkAs34BOYU/qusrgFx8b4mbpqF0jnrGySHA9CgGY2twfS2+GgPJmrfd+Da66b/F3/rshYrjWzeoq4FDJRXmAvaFQtf7dBno7t5JxwGFhu2>
    POSTGRES_PASSWORD: AgBenSkoGDMXUsMz76tU0sinsADDYKBz+HgtZQKLogNf5vZw7XzQ20osSpR8iY+ZSo7ou4ISWVueEpb3yBE9sLwWM058i5/45XJNhO/qBgNyc3TS4NaD+TzSNVUDN+MRkcGoPnNg>
    POSTGRES_USER: AgAZVT/JORmulQTj5ouyxFk0lzg6r9DjCrBJd/eEtfoXuC14yseL1OjkWNARoKR+Ggg34PHubKiK5SUvjuKQokxW/vYVPaCSkchh7XHxrZl9bqQCLGVUh0dc8/mLnKRyUQJDI0vcDMat>
  template:
    metadata:
      creationTimestamp: null
      name: stock-db-secret
      namespace: stock