  GNU nano 7.2                                                          stock-kis-secret.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: stock-kis-secret
  namespace: stock
spec:
  encryptedData:
    KIS_APP_KEY: AgAFA2MISD/TVTtUOvR7AyAKnOIto4z7WDL1g8CYHIgyo9G2ZgdtLt7cZM7AZwOCLHFjx2kEFNcUwSckHnAK2fSRHMikwG0eGDj5zI3MBj6z2cBPZ/xtNIJTByn3t9JjUVvISKBPepj1/p>
    KIS_APP_SECRET: AgA254/MTRNsHWkSlULA3gmqmzm5SG3JTwXxGss6i7SkyH37i5wQkR/8Jfmerya77AS8nDyqztl6qRBLntRrdMWT0vvmaDor4POlN4AQROQ+FaVPSDjSmZecvIWEgRdaJTrjuoKS1TH>
    KIS_MOCK: AgBpAX1vZMAdfLIfPje5mi9kib/ipXbOByaHgHjaoRPMXhPZuCVJkO2dx7ZI4sil1GPq3VlIiB3Eacr4ViUn05rQ4YxojRmSGKkN5Wuoj6H+C90ZsT5CTWyYipZlFabbJrGy7d8LonFGHiMj/>
  template:
    metadata:
      creationTimestamp: null
      name: stock-kis-secret
      namespace: stock
