---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: stock-api-secrets
  namespace: stock
spec:
  encryptedData:
    GEMINI_API_KEY: AgAFy5TSq2wZyhLf+74V6fhW+u/TSIkWY9FiVrccRlWoe5gBirc4UgWB2j8xJ23ERoS0mp9qVjGW5Lgd2RVFYj8B5qjkruERkT0tRWZJ82DGnvj/6qw1oc0aJLeLgD8eCapc9hviqIe>
    NEWS_API_KEY: AgAEUlImBmUuijQajnU6KX8i2T1PxAUiGtojlEYVKAuZ2caVtLDc+DHNDXH+8mho0P66V1stPHJOA93dyvfSM380WVuZViAmnPPq3y3Vk0hzsasZjC01yo1QxURSkexUp1q77zcT8T6jN>
  template:
    metadata:
      creationTimestamp: null
      name: stock-api-secrets
      namespace: stock
