---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: stock-auth-secret
  namespace: stock
spec:
  encryptedData:
    JWT_SECRET: AgAwVi/h90naPMA6lvh1OsAeswQMmRK5EPXFvd/3slE+0znNm1v2Rkmv55wiBg7cdLlIuk2vfU/v474xdqIG47T15IgDbON8MWz8akWsy+nsgP+L0UJA/uvTjApoiX1/FfA7B7T3GJf/LiJwXe8dfvLAw3cJK9Zl2D8S2aY3YIlMNNDmu8Pa1c+QORgDa/+E9Pi9rsXA7Y4d97K/2qVZfYiS/bNVU3DPBQV4G7Qqml352VpeSeq6K6xGoty7uqduF/oMJF6MbwhJR3SCa0UnJoLeCoZUIvzHegPT643g6b6yKnOHOuLRzfsswn9K5bZVHKfp8T9AzUlyNdn7ytj+DV8560ay5NpYGHY8VjNGYFgBQxrRLut3nhdBmZhXCqNZKe1NqZ5DKL27ECUw/FBf36FwL2/bF9ZXrt0OxgebReuwmirJOd3z5MZNGYqF/IKxgkWSymfxbNoAy4QTix82TQoM9OzBXwfnMsnq/RYY6d1tHnKAfBPQaE17QbJyymvuVCEZk6RBo7IxQm/f5OD0eQ93VPsseYYhKUYofhudno6YBggjLlTWzVgvtpLAj6sJ1N1G49rR9Hz/LxBEZPJobyLrFrgqWBPJ1mw0DUx563GEmPe0IPcbWP5FkAe6Bjmne6kDzyWx8/BQvHJmTGIOhed6U5Xtg9QdiygTs16UDyGAGM3rHSeSFj4WoNfFtLSbijCuPWND35xsq1uNLNIcL45lCSp58Q+xZ1HmILv+1bUM+3wP9dFNnM194PDXcQX5Q6KyQt3ibNl4FquRhlvNWQXI
  template:
    metadata:
      creationTimestamp: null
      name: stock-auth-secret
      namespace: stock
