---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: stock-auth-secret
  namespace: stock
spec:
  encryptedData:
    JWT_SECRET: AgAACJp2tfjzOgfpDjlIm0SmDQJebVj+Iu2RrdmR2wN+GtK4XJC3sstdj/56+lE8k2T9MoQARw8nMnHvgiopuFEBrRIYNYORPEizZwjSCbWL1n+5i0AW4pQo/L4SJdvmAX5sz88v/q27YunNLdxYmn2NhJpSB+ncZv0knRCgm/rMpu2G8ZKaD4HoxnpXPufEI7SugEfIUd5ww432BNkxHNKBX6bCO0ph9MmDtbh4rRhPao48Vxx7mm8o7c8NHncsOGX+xvH8A34nbuwW6sTaYZ6X54Xid8uW1XrJz1QJQwyaRD5JZCponWfbMP0W5y/Rwuv8hVZRjVdFFKDj2bP3QA2TcEivesmcknGXSjIs+KbWF6Gvc869O8EmQE9HO8PEf7HbifWb1MBAuxeKvksf7c6NgK+BzqkR/ezE/I8vUnzbxZtqmVePH8P6aLi95ojMjs8+bwzNxJOgCBIztsmLn9qneuRcTtmQFAr9JHZdh8m2Rzv7rd7B1PYpVF2e22HDWVQxgRf+g8Ybrii7NH/RzzGiD2loGn9A0Vh7vDhf7a8lh13YjJpNw8ceUuPX1VfCRhlu0P4BU2kTDEpk8wFrz9vmsAjOX4QlMDJWpqby3zUJgbQpPAUPBEN9Wr9sL75V95ecfjRZkzzIKCyQiDDXFzHrO5pPdamLpqmpqFrnzuQPqBboTGE09WltynEiBadgzUila/ubAtP9/ksg2Cu/YnY5U27N5p1tpCY3UjSZ0ekN93ZHhWMAK6nwRhB4RVeLUFOJcPM5AXeOJ/gFxgc2aDs9
  template:
    metadata:
      creationTimestamp: null
      name: stock-auth-secret
      namespace: stock
